---
layout: base
---

Legal & Privacy Terms of Service
--------------------------------

Gluster.org Legal Information
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Copyright &copy; 2005-2012, Red Hat, Inc.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Copyrights of all content and contributions on http://www.gluster.org and
http://community.gluster.org are by their authors, licensed under a
http://creativecommons.org/licenses/by-sa/3.0/[Creative Commons
Attribution-ShareAlike 3.0 Unported License].  Specifications subject
to change without notice.

GlusterFS, the Gluster ant logo, and the Gluster Community logo are
all trademarks of Red Hat, Inc. All other trademarks, registered
trademarks, and product names may be trademarks of their respective
owners.

GlusterFS versions 3.1.0 - 3.1.5 and 3.2.0 - 3.2.2 are released under
the http://www.gnu.org/licenses/agpl.html[GNU Affero General Public
License version 3].

All other versions of GlusterFS are released under the
http://www.gnu.org/licenses/gpl.html[GNU General Public License
version 3].

Official documentation is released under the
http://www.gnu.org/licenses/fdl.html[GNU Free Documentation License
1.2 or later].

Privacy Policy
~~~~~~~~~~~~~~

We take your privacy seriously at Gluster. Any information that is
collected by Gluster.org will be used only for internal business
purposes to better serve your needs. We will not disclose any personal
information to a third party without your prior consent, nor will we
sell, lease, or trade your personal information to others.  Export
Regulations

By downloading GlusterFS, you agree to comply with the following terms
and conditions:

By downloading GlusterFS, you acknowledge that you understand all of
the following: GlusterFS software and technical information may be
subject to the U.S. Export Administration Regulations (the "EAR") and
other U.S. and foreign laws and may not be exported, re-exported or
transferred (a) to any country listed in Country Group E:1 in
Supplement No. 1 to part 740 of the EAR (currently, Cuba, Iran, North
Korea, Sudan & Syria); (b) to any prohibited destination or to any end
user who has been prohibited from participating in U.S. export
transactions by any federal agency of the U.S. government; or (c) for
use in connection with the design, development or production of
nuclear, chemical or biological weapons, or rocket systems, space
launch vehicles, or sounding rockets, or unmanned air vehicle
systems. You may not download GlusterFS software or technical
information if you are located in one of these countries or otherwise
subject to these restrictions. You may not provide GlusterFS software
or technical information to individuals or entities located in one of
these countries or otherwise subject to these restrictions. You are
also responsible for compliance with foreign law requirements
applicable to the import, export and use of GlusterFS software and
technical information.  Questions

Please link:/interact/[contact us] if you have any questions about the Gluster legal or
privacy policy.

