---
title: How to write documentation?
---

=== Formatting and file placement

Gluster Docs are inside *source/documentation/* folder of the
gluster-site git tree. The documentation "frontpage" is
source/documentation/index.html.haml and you can add docs either under
documentation/ or if you wish, you can organize stuff in
subfolders, but there are two things to keep in mind: 

  * We are using "directory indexes" mode, to get nicer looking urls.
    In practice this means documentation/foobar.html becomes
    documentation/foobar/ in the site. This could be slightly
    confusing at first, and also gives you the restriction, that you
    should not have foobar.html and foobar/index.html as their
    destination urls would clash.

  * The navigation is to be generated by hand. This is explained in 
    detail further on.

The documents are actually asciidoc or markdown or whatever you
wish. I am pretty sure if a document format exists, there likely is a
ruby module for parsing it. However, the example files are asciidoc.

The naming convention is foobar.html.adoc - and the files'
"frontmatter" (the stuff between the three dashes in the beginning)
specify the title of the file, that gets displayed in the web page
title and also as a headline in the beginning of the page, so please
ensure each page defines its title.

=== Navigation 

The navigation is generated from docs.yml file under data/. It
supports just one level of depth in the navigation list, so you can
have section headers and documents. Here's an example:

----

- Getting Started:
  Quickstart!: /documentation/quickstart/
  Getting Started, more in depth: /documentation/getting_started/
  GlusterFS Concepts & Architecture: /documentation/architecture/
- Further Reading:
  Document in a Subfolder: /documentation/foobar/otherdoc/
- This is a Header:
  This is an article: /this/is/the/url
  This is another article: /this/is/the/url
----

The indentation is nothing for section headers and two spaces for
documents. Let me know if this doesnt work for you and you need to
have deeper structure. However note that you should do it so that you
have sections to organize stuff, no matter how they are located on disk.

To test docs run

  bundle exec middleman

..and the site on localhost:4567 automatically refreshes when the
content changes, which is pretty nice.

