name: Gluster Website
title: GLUSTER - Massive storage for your Cloud.
org: gluster community

profiles:
  staging:
    base_url: 'http://staging.gluster.org'
    minify: false
  devel:
    base_url: 'http://localhost:4242'
    minify: false
  final:
    base_url: 'http://www.gluster.org'
    minify: true
