name: Gluster Website
title: GLUSTER - Massive storage for your Cloud.
org: gluster community
base_url: 'http://www.gluster.org'

profiles:
  development:
    base_url: 'http://localhost:4242'
    minify: false
    dev: true
    deploy:
      dummy:
  staging:
    base_url: http://staging.gluster.org
    minify: true
    deploy:
       dummy:
       # we have a local git pull via cron on 
       # the staging pulling updates for now
  production:
    base_url: http://www.gluster.org
    minify: true
    deploy:
       dummy:
#      host: user@myblog.com
#      path: /home/user/path/to/site
