name: Gluster Website
title: GLUSTER - Massive storage for your Cloud.
org: gluster community

profiles:
  staging:
    base_url: 'http://staging.gluster.org'
    minify: false
  devel:
    base_url: 'http://localhost:4242'
    minify: false
  forge:
    base_url: 'https://forge.gluster.org/gluster-site/gluster-site/blobs/raw/master/_site/'
  final:
    base_url: 'http://www.gluster.org'
    minify: true
