name: Project Name
title: Baked with Awestruct
org: Organization
base_url: 'http://www.gluster.org'

profiles:
  development:
    base_url: 'http://localhost:4242'
    minify: false
    dev: true
    deploy:
      dummy:
  production:
    base_url: http://www.myblog.com
    minify: true
#    deploy:
#      host: user@myblog.com
#      path: /home/user/path/to/site
