name: Gluster Website
title: Gluster.org
org: gluster community
base_url: 'http://www.gluster.org'

profiles:
  development:
    base_url: 'https://forge.gluster.org/gluster-site/gluster-site/blobs/raw/master/_site/'
    minify: false
    dev: true
    deploy:
      dummy:
  staging:
    base_url: http://staging.gluster.org
    minify: true
    deploy:
       dummy:
#      host: download.gluster.org
#      path: /var/www/www.gluster.org-staging
  production:
    base_url: http://www.gluster.org
    minify: true
    deploy:
       dummy:
#      host: user@myblog.com
#      path: /home/user/path/to/site
