---
layout: docs
navigation: documentation
---

== GlusterFS In Brief

GlusterFS is a *distributed file system* capable of scaling to several
petabytes (actually, 72 brontobytes!) and handling thousands of
clients simultaneously.

GlusterFS combines blocks of storage over the network into a single,
large storage pool that is served to client appliances. Gluster can
deliver *exceptional performance* for diverse workloads.

GlusterFS is *free and open source software* enabling people like you
to build data storage with high performance and great value, for a
variety of demanding applications.

[[performance_link]]
=== Performance Hilights

_Why does Gluster perform so well? We could list a few success stories /
references here and the reasons why they chose to use glusterfs._

_We could then give a few examples of the kind of uses Gluster makes
sense for and what kind of hardware is realistically required to
achieve that._

[[requirements_link]]
=== Client Connectivity Requirements 

Gluster is compatible with all major desktop operating
systems. Windows, Mac and Linux hosts can all connect to a Gluster
share. There are several options and protocols available: 
